description = "Embedded Web Server"
long-description = """

EWS is a web server construction kit, designed for embedded applications using the GNAT Ada compiler.

The project is hosted on [Github](https://github.com/simonjwright/ews).

"""
name = "ews"
version = "2022"
authors = ["Simon Wright <simon@pushface.org>"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]
project-files = ["ews.gpr"]
tags = ["web", "server"]
website = "https://github.com/simonjwright/ews"

[[depends-on]]
xmlada = "any"

[gpr-externals]
LIBRARY_TYPE = ["relocatable", "static"]

[configuration]
disabled = true
